name = "Goyo"
description = "A simplicity and clean documentation theme"
tags = ["documentation", "Multilingual", "Responsive", "minimal"]
license = "MIT"
homepage = "https://github.com/hahwul/goyo"
# The minimum version of Zola required
min_version = "0.17.0"
# An optional live demo URL
demo = "https://goyo.hahwul.com"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "hahwul"
homepage = "https://www.hahwul.com"
