---
name: Contributors
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: manual run
        required: false
        default: ""
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: false
          includeBots: true
