---
name: CI
on:
  pull_request:
    branches: [main]
    paths: ["**/*.cr", shard.yml]
  workflow_dispatch:
    inputs:
      logLevel:
        description: manual run
        required: false
        default: ""
jobs:
  build-crystal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version: [1.15.0, 1.16.0, 1.17.0, 1.18.0]
    steps:
      - uses: actions/checkout@v5
      - uses: MeilCli/setup-crystal-action@v4
        with:
          crystal_version: ${{ matrix.crystal-version }}
      - name: Install dependencies
        run: shards install
      - name: Build
        run: shards build
  lint:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v5
      - name: Crystal Ameba Linter
        id: crystal-ameba
        uses: crystal-ameba/github-action@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    container:
      image: 84codes/crystal:latest-debian-12
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
